CREATE SCHEMA IF NOT EXISTS `sic` DEFAULT CHARACTER SET utf8 ;
USE `sic` ;

CREATE TABLE IF NOT EXISTS tbl_usuario (
	usuid INT NOT NULL AUTO_INCREMENT,
	usunombre VARCHAR(45) NOT NULL,
	usucontrasena VARCHAR(25) NOT NULL,
	usuultimasesion DATE,
	usuestatus VARCHAR(1) NOT NULL,
	usunombrereal VARCHAR(60),
	usucorreoe VARCHAR(60),
	usutelefono VARCHAR(25),
	usudireccion VARCHAR(80),
	PRIMARY KEY (usuid) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_cliente (
	idc INT NOT NULL AUTO_INCREMENT,
	nombrec VARCHAR(45) NOT NULL,
	direccionc VARCHAR(45) NOT NULL,
	nitc VARCHAR(45) NOT NULL,
	telefonoc VARCHAR(45) NOT NULL,
	codivendec VARCHAR(45) NOT NULL,
	estadoc VARCHAR(45) NOT NULL,
	
	PRIMARY KEY (idc) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_vendedor (
	idv INT NOT NULL AUTO_INCREMENT,
	nombrev VARCHAR(45) NOT NULL,
	direccionv VARCHAR(45) NOT NULL,
	nitv VARCHAR(45) NOT NULL,
	telefonov VARCHAR(45) NOT NULL,
	estadov VARCHAR(45) NOT NULL,
	
	PRIMARY KEY (idv) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_proveedor (
	idp INT NOT NULL AUTO_INCREMENT,
	nombrep VARCHAR(45) NOT NULL,
	direccionp VARCHAR(45) NOT NULL,
	telefonop VARCHAR(45) NOT NULL,
	nitp VARCHAR(45) NOT NULL,
	estadop VARCHAR(45) NOT NULL,
	PRIMARY KEY (idp) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_productos (
	idpr INT NOT NULL AUTO_INCREMENT,
	nombrepr VARCHAR(45) NOT NULL,
	colineapr VARCHAR(45) NOT NULL,
	comarcapr VARCHAR(45) NOT NULL,
	estadopr VARCHAR(45) NOT NULL,
	existenpr VARCHAR(45) NOT NULL,
	PRIMARY KEY (idpr) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_linea (
	idl INT NOT NULL AUTO_INCREMENT,
	nombrel VARCHAR(45) NOT NULL,
	estadol VARCHAR(45) NOT NULL,
	
	PRIMARY KEY (idl) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_marca (
	idm INT NOT NULL AUTO_INCREMENT,
	nombrem VARCHAR(45) NOT NULL,
	estadom VARCHAR(45) NOT NULL,
	
	PRIMARY KEY (idm) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_bodega (
	idb INT NOT NULL AUTO_INCREMENT,
	nombreb VARCHAR(45) NOT NULL,
	estadob VARCHAR(45) NOT NULL,
	
	PRIMARY KEY (idb) )
ENGINE = InnoDB CHARACTER SET = latin1;


