/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;


import seguridad.modelo.daoProducto;
import seguridad.controlador.clsProductos;
import seguridad.modelo.daoLinea;
import seguridad.controlador.clsLinea;
import seguridad.modelo.daoMarca;
import seguridad.controlador.clsMarca;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;

/**
 *
 * @author visitante
 */
public class frmMantenimientoProducto extends javax.swing.JInternalFrame {


    public void estados() {    
        cbox_estado.addItem("seleccione: "); 
        cbox_estado.addItem("activo");
        cbox_estado.addItem("inactivo");
        cbox_estado.addItem("suspendido");
    }
 
    public void llenadoDeCombosLinea() {
        daoLinea pDAO = new daoLinea();
        List<clsLinea> ps = pDAO.select();
        cbox_linea.addItem("Seleccione una linea");
        for (int i = 0; i < ps.size(); i++) {
            cbox_linea.addItem(ps.get(i).getnombrel());
        }
    }
    
     public void llenadoDeCombosMarca() {
        daoMarca mDAO = new daoMarca();
        List<clsMarca> ms = mDAO.select();
        cbox_marca.addItem("Seleccione una marca");
        for (int i = 0; i < ms.size(); i++) {
            cbox_marca.addItem(ms.get(i).getnombrem());
        }
    }
    
    

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("codigo");
        modelo.addColumn("nombre");
        modelo.addColumn("codigo linea");
        modelo.addColumn("codigo marca");
        modelo.addColumn("estado");
        modelo.addColumn("existencias");
        
        daoProducto mDAO = new daoProducto();
        List<clsProductos> m = mDAO.select();
        tablaVendedores.setModel(modelo);
        String[] dato = new String[10];
        for (int i = 0; i < m.size(); i++) {
            dato[0] = Integer.toString(m.get(i).getidpr());
            dato[1] = m.get(i).getnombrepr();
            dato[2] = m.get(i).getcolineapr();
            dato[3] = m.get(i).getcomarcapr();
            dato[4] = m.get(i).getestadopr();
            dato[5] = m.get(i).getexistenpr();
        

            modelo.addRow(dato);
        }
    }

    public void buscarCliente() {
        clsProductos cAConsultar = new clsProductos();
        daoProducto cDAO = new daoProducto();
        cAConsultar.setidpr(Integer.parseInt(txtbuscado.getText()));
        cAConsultar = cDAO.query(cAConsultar);
        txtNombre.setText(cAConsultar.getnombrepr());
        cbox_linea.setSelectedItem(cAConsultar.getcolineapr());
        cbox_marca.setSelectedItem(cAConsultar.getcomarcapr());
        cbox_estado.setSelectedItem(cAConsultar.getestadopr());
        txtExistencias.setText(cAConsultar.getexistenpr());
    }

    public frmMantenimientoProducto() {
        initComponents();
        llenadoDeTablas();
        estados();
        llenadoDeCombosMarca();
        llenadoDeCombosLinea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label6 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        cbox_estado = new javax.swing.JComboBox<>();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        cbox_marca = new javax.swing.JComboBox<>();
        cbox_linea = new javax.swing.JComboBox<>();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento Clientes");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 95, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 95, -1));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("datos");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 95, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Nombre");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 102, -1));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtNombre.setOpaque(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, -1));

        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo ", "nombre", "codigo linea", "codigo marca", "estado", "existencias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 30, 640, 303));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 34, -1, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("estado");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, -1));

        cbox_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_estadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, 20));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("Codigo linea");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Codigo Marca");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtExistencias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtExistencias.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtExistencias.setOpaque(false);
        getContentPane().add(txtExistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("Existencias");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cbox_marca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_marcaActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, 20));

        cbox_linea.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_lineaActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        daoProducto eDAO = new daoProducto();
        clsProductos eAEliminar = new clsProductos();
        eAEliminar.setidpr(Integer.parseInt(txtbuscado.getText()));
        eDAO.delete(eAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoProducto eDAO = new daoProducto();
        clsProductos eAInsertar = new clsProductos();
        eAInsertar.setnombrepr(txtNombre.getText());
        eAInsertar.setcolineapr(cbox_linea.getSelectedItem().toString());
        eAInsertar.setcomarcapr(cbox_marca.getSelectedItem().toString());
        eAInsertar.setestadopr(cbox_estado.getSelectedItem().toString());
        eAInsertar.setexistenpr(txtExistencias.getText());
       
        eDAO.insert(eAInsertar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
//        // TODO add your handling code here:
        daoProducto eDAO = new daoProducto();
        clsProductos eAActualizar = new clsProductos();
        eAActualizar.setidpr(Integer.parseInt(txtbuscado.getText()));
        eAActualizar.setnombrepr(txtNombre.getText());
        eAActualizar.setcolineapr(cbox_linea.getSelectedItem().toString());
        eAActualizar.setcomarcapr(cbox_marca.getSelectedItem().toString());
        eAActualizar.setestadopr(cbox_estado.getSelectedItem().toString());
        eAActualizar.setexistenpr(txtExistencias.getText());
        eDAO.update(eAActualizar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed


        txtNombre.setText("");
         cbox_linea.setSelectedIndex(0);
          cbox_marca.setSelectedIndex(0);
        txtExistencias.setText("");
        cbox_estado.setSelectedIndex(0);
        txtbuscado.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbox_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_estadoActionPerformed

    private void cbox_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_marcaActionPerformed

    private void cbox_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_lineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_lineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbox_estado;
    private javax.swing.JComboBox<String> cbox_linea;
    private javax.swing.JComboBox<String> cbox_marca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
