/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;


import seguridad.modelo.daoCliente;
import seguridad.controlador.clsCliente;
import seguridad.modelo.daoVenta;
import seguridad.controlador.clsVenta;
import seguridad.modelo.daoProducto;
import seguridad.controlador.clsProductos;
import seguridad.modelo.daoBodega;
import seguridad.controlador.clsBodega;
import seguridad.modelo.daoVendedor;
import seguridad.controlador.clsVendedor;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author visitante
 */
public class frmVentas extends javax.swing.JInternalFrame {




  public void productos() {
        daoProducto notasDAO = new daoProducto();
        List<clsProductos> notas = notasDAO.select();
        buscaProducto.addItem("Seleccione una opción");
        for (int i = 0; i < notas.size(); i++) {
            buscaProducto.addItem(notas.get(i).getnombrepr());
        }
    }
    
  
   public void clientes() {
        daoCliente notasDAO = new daoCliente();
        List<clsCliente> notas = notasDAO.select();
        buscaCliente.addItem("Seleccione una opción");
        for (int i = 0; i < notas.size(); i++) {
            buscaCliente.addItem(notas.get(i).getnombrec());
        }
    }
   
   public void bodega() {
        daoBodega notasDAO = new daoBodega();
        List<clsBodega> notas = notasDAO.select();
        buscaBodega.addItem("Seleccione una opción");
        for (int i = 0; i < notas.size(); i++) {
            buscaBodega.addItem(notas.get(i).getnombreb());
        }
    }
   
   
     public void vendedor() {
        daoVendedor notasDAO = new daoVendedor();
        List<clsVendedor> notas = notasDAO.select();
        buscaVende.addItem("Seleccione una opción");
        for (int i = 0; i < notas.size(); i++) {
            buscaVende.addItem(notas.get(i).getnombrev());
        }
    }
   

     public void buscar_producto() {
        clsProductos notasAConsultar = new clsProductos();
        daoProducto notasDAO = new daoProducto();
        
        notasAConsultar.setnombrepr(buscaProducto.getSelectedItem().toString());
        notasAConsultar = notasDAO.queryn(notasAConsultar);
    
        txtvalor.setText(notasAConsultar.getvalorpr());     
        }
     
   public void agregaValores(Stack pila){
    txtproductos.setText(String.valueOf(pila));
    }
   
    public void agrega(Stack pila2){
    txtproductosuni.setText(String.valueOf(pila2));
    }
     
   public void proceso(){
  
    double valorproducto;
    double cantidad, cantidadt;
    valorproducto=Double.parseDouble(txtvalor.getText());       
    cantidad=Double.parseDouble(txtcantidad.getText());   
    cantidadt=Double.parseDouble(txtpcantidad.getText());  
    Double numero1= Double.parseDouble(txtsaldo.getText());

    double  r1; 
    double  r2; 
    
    if(cantidad>cantidadt){
    
    r1 = cantidad* valorproducto;
    
    txtpcantidad.setText(String.valueOf(cantidad + cantidadt));
    txtsaldo.setText(String.valueOf(r1 + numero1));
    
    } else if(cantidad<cantidadt){
   
     r1 = cantidad* valorproducto;
    
    txtsaldo.setText(String.valueOf(r1 + numero1));
    txtpcantidad.setText(String.valueOf(cantidad + cantidadt));
   }  
    else if(cantidad==cantidadt){
   
     r1 = cantidad* valorproducto;
    
    txtsaldo.setText(String.valueOf(r1 + numero1));
    txtpcantidad.setText(String.valueOf(cantidad + cantidadt));
   }  
  
   
   
    }
   
   
     
     
    public frmVentas() {
        initComponents();
        productos();
         clientes();
          bodega();
           vendedor();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        buscaProducto = new javax.swing.JComboBox<>();
        label3 = new javax.swing.JLabel();
        btnBuscaProducto = new javax.swing.JButton();
        label4 = new javax.swing.JLabel();
        buscaCliente = new javax.swing.JComboBox<>();
        label5 = new javax.swing.JLabel();
        buscaBodega = new javax.swing.JComboBox<>();
        label6 = new javax.swing.JLabel();
        buscaVende = new javax.swing.JComboBox<>();
        label7 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        txtproductos = new javax.swing.JTextField();
        txtpcantidad = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        label12 = new javax.swing.JLabel();
        txtproductosuni = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("venta ");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscaProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buscaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaProductoActionPerformed(evt);
            }
        });
        getContentPane().add(buscaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 20));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Seleccionar producto");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnBuscaProducto.setText("buscar");
        btnBuscaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        label4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label4.setText("Seleccione cliente");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        buscaCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(buscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 150, 20));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("bodega donde se efectua ");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        buscaBodega.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buscaBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaBodegaActionPerformed(evt);
            }
        });
        getContentPane().add(buscaBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 20));

        label6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label6.setText("Vendedor");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        buscaVende.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buscaVende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaVendeActionPerformed(evt);
            }
        });
        getContentPane().add(buscaVende, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 20));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label7.setText("valor");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, 30));

        txtvalor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtvalor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtvalor.setOpaque(false);
        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        txtcantidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtcantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtcantidad.setOpaque(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 30, 30));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("cantidad");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 106, -1, 20));

        add.setText("agrega");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label9.setText("saldo a cobrar");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label10.setText("Productos");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        txtproductos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtproductos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtproductos.setOpaque(false);
        txtproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductosActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 220, 30));

        txtpcantidad.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtpcantidad.setText("0");
        txtpcantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtpcantidad.setEnabled(false);
        txtpcantidad.setOpaque(false);
        txtpcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtpcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 220, 20));

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label11.setText("cantidad de productos vendidos");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        txtsaldo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtsaldo.setText("0");
        txtsaldo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtsaldo.setEnabled(false);
        txtsaldo.setOpaque(false);
        getContentPane().add(txtsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 220, 20));

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("valor unidad");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        txtproductosuni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtproductosuni.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtproductosuni.setOpaque(false);
        txtproductosuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductosuniActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductosuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 220, 30));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 290, 50));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setEnabled(false);
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 290, 340));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setEnabled(false);
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProductoActionPerformed

Stack<String> pila = new Stack<String>();
Stack<String> pila2 = new Stack<String>();
int nagregados = 1; int n;
    private void btnBuscaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProductoActionPerformed
        // TODO add your handling code here:
buscar_producto();
    }//GEN-LAST:event_btnBuscaProductoActionPerformed

    private void buscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaClienteActionPerformed

    private void buscaBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaBodegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaBodegaActionPerformed

    private void buscaVendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaVendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaVendeActionPerformed

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
  
        
     String nameCursos; 
        nameCursos = buscaProducto.getSelectedItem().toString(); 
        pila.push(nameCursos); 
        agregaValores(pila); 
        
        
        String name; 
        name = buscaProducto.getSelectedItem().toString()+ ": " + txtvalor.getText() ; 
        pila2.push(name); 
        agrega(pila2); 
        
proceso();
        
        
   n = nagregados++;
   txtvalor.setText("");
    txtcantidad.setText("");    
        
        
    }//GEN-LAST:event_addActionPerformed

    private void txtproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductosActionPerformed

    private void txtpcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpcantidadActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        daoVenta notasDAO = new daoVenta();
        clsVenta notasAInsertar = new clsVenta();
        notasAInsertar.setproductove(String.valueOf(pila));
        notasAInsertar.setvalorpve(txtproductosuni.getText());
        notasAInsertar.setcantidadve(txtpcantidad.getText());
        notasAInsertar.setclienteve(buscaCliente.getSelectedItem().toString());
        notasAInsertar.setvalorve(txtsaldo.getText());
        notasAInsertar.setbodegave(buscaBodega.getSelectedItem().toString());
        notasAInsertar.setvendedorve(buscaVende.getSelectedItem().toString());
        // aqui falta el valor
        notasDAO.insert(notasAInsertar);

     

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtproductosuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductosuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductosuniActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        int contador = 1;

        while(contador <= n){
            if(!pila.empty()){
                pila.pop();
                agregaValores(pila);
            }
             if(!pila2.empty()){
                pila2.pop();
                agrega(pila2);
            }
            
            contador++;
        }

        txtvalor.setText("");
        txtcantidad.setText("");
        txtpcantidad.setText("0");
        txtsaldo.setText("0");
     txtproductos.setText("");
      txtproductosuni.setText("");
        buscaProducto.setSelectedIndex(0);
        buscaCliente.setSelectedIndex(0);
        buscaBodega.setSelectedIndex(0);
        buscaVende.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnBuscaProducto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> buscaBodega;
    private javax.swing.JComboBox<String> buscaCliente;
    private javax.swing.JComboBox<String> buscaProducto;
    private javax.swing.JComboBox<String> buscaVende;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtpcantidad;
    private javax.swing.JTextField txtproductos;
    private javax.swing.JTextField txtproductosuni;
    private javax.swing.JTextField txtsaldo;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
