/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;

import java.awt.Dimension;

/**
 *
 * @author visitante
 */
public class mdiGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MdiGeneral
     */
    public mdiGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(mdiGeneral.MAXIMIZED_BOTH);
        this.setTitle("Módulo Seguridad");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mantenimiento0 = new javax.swing.JMenuItem();
        Mantenimiento1 = new javax.swing.JMenuItem();
        Mantenimiento2 = new javax.swing.JMenuItem();
        mantenimiento3 = new javax.swing.JMenuItem();
        mantenimiento4 = new javax.swing.JMenuItem();
        mantenimiento5 = new javax.swing.JMenuItem();
        jM_MantenimientopApps = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu4.setText("Catalogos");

        mantenimiento0.setText("Mantenimiento Usuarios");
        mantenimiento0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimiento0ActionPerformed(evt);
            }
        });
        jMenu4.add(mantenimiento0);

        Mantenimiento1.setText("Mantenimiento 1");
        Mantenimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mantenimiento1ActionPerformed(evt);
            }
        });
        jMenu4.add(Mantenimiento1);

        Mantenimiento2.setText("Mantenimiento 2");
        Mantenimiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mantenimiento2ActionPerformed(evt);
            }
        });
        jMenu4.add(Mantenimiento2);

        mantenimiento3.setText("Mantenimiento 3");
        mantenimiento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimiento3ActionPerformed(evt);
            }
        });
        jMenu4.add(mantenimiento3);

        mantenimiento4.setText("Mantenimiento 4");
        mantenimiento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimiento4ActionPerformed(evt);
            }
        });
        jMenu4.add(mantenimiento4);

        mantenimiento5.setText("Mantenimiento 5");
        mantenimiento5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimiento5ActionPerformed(evt);
            }
        });
        jMenu4.add(mantenimiento5);

        jMenuBar1.add(jMenu4);

        jM_MantenimientopApps.setText("Procesos");
        jMenuBar1.add(jM_MantenimientopApps);

        jMenu6.setText("Reportes");
        jMenuBar1.add(jMenu6);

        jMenu8.setText("Ayudas");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mantenimiento0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimiento0ActionPerformed
        frmMantenimientoUsuarios ventana = new frmMantenimientoUsuarios();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);        // TODO add your handling code here:
    }//GEN-LAST:event_mantenimiento0ActionPerformed

    private void Mantenimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mantenimiento1ActionPerformed
        // TODO add your handling code here:
         frmMantenimiento1 ventana = new frmMantenimiento1();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);      
        
        
    }//GEN-LAST:event_Mantenimiento1ActionPerformed

    private void Mantenimiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mantenimiento2ActionPerformed
        // TODO add your handling code here:
              frmMantenimiento2 ventana = new frmMantenimiento2();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);      
        
    }//GEN-LAST:event_Mantenimiento2ActionPerformed

    private void mantenimiento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimiento3ActionPerformed
        // TODO add your handling code here:
           frmMantenimiento3 ventana = new frmMantenimiento3();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);      
        
    }//GEN-LAST:event_mantenimiento3ActionPerformed

    private void mantenimiento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimiento4ActionPerformed
        // TODO add your handling code here:
           frmMantenimiento4 ventana = new frmMantenimiento4();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);      
        
    }//GEN-LAST:event_mantenimiento4ActionPerformed

    private void mantenimiento5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimiento5ActionPerformed
        // TODO add your handling code here:
           frmMantenimiento5 ventana = new frmMantenimiento5();
        jDesktopPane1.add(ventana);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);      
        
    }//GEN-LAST:event_mantenimiento5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mantenimiento1;
    private javax.swing.JMenuItem Mantenimiento2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jM_MantenimientopApps;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mantenimiento0;
    private javax.swing.JMenuItem mantenimiento3;
    private javax.swing.JMenuItem mantenimiento4;
    private javax.swing.JMenuItem mantenimiento5;
    // End of variables declaration//GEN-END:variables
}
